import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ShoppingCartModal from "./components/ShoppingCartModal";
import Navbar from "./components/Navbar";
import CartProvider from "./components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "D's Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <Navbar />
          <ShoppingCartModal/>
          {children}
        </CartProvider>
        </body>
    </html>
  );
}
